<?php


namespace App\Controller;


use App\Entity\Articles;
use App\Form\ArticleType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ArticlesController extends AbstractController
{

    /**
     * @Route("member/addArticle", name="article_add")
     */
    public function addArticle(Request $request)
    {
        $article = new Articles();

        $user = $this->getUser();

        $form = $this->createForm(ArticleType::Class, $article, []);
        $form->handleRequest($request);

        if( $form->isSubmitted() && !$form->isEmpty() && $form->isValid())
        {
            if($article->getArticlePicture() != '' || $article->getArticlePicture() != null ){
                //ajout d'une photo
                $file = $form->get('articlePicture')->getData();
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                try {
                    $file->move(
                        $this->getParameter('article_pictures_directory'),
                        $fileName
                    );
                } catch (FileException $e) {
                    $this->addFlash('error', 'Un problème est survenue sur la photo de l\'article lors de l\'enregistrement!');

                    return $this->redirectToRoute('article_add', []);
                }
            }
            else{
                $fileName = '';
            }

            $article->setArticlePicture($fileName);
            $article->setArticleCreateAt(new \DateTime()) ;
            $article->setArticleUser($user);
            $article->setArticleValid('waiting_validation');


            $doctrine = $this->getDoctrine();
            $entityManager = $doctrine->getManager();

            $entityManager->persist($article);
            $entityManager->flush();

            $this->addFlash('success', 'Votre Article a bien été enregistré, il sera publié après validation!');

            return $this->redirectToRoute('profil_index',[]);

        }
        return $this->render('member/article_add.html.twig',[
            'formAjoutarticle' => $form->createView(),
        ]);
    }

    /**
     * @Route("/news", name="news_article")
     */
    public function index()
    {
        $doctrine = $this->getDoctrine();

        $userRepository = $doctrine->getRepository(Articles::class);
        $resultatedit= $userRepository->findAll();

        return $this->render('home/new_articles.html.twig',[
                'resultatedit' => $resultatedit
            ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}