security:
    providers:
        users:
            entity:
                class: 'App\Entity\Users'
                property: 'userEmail'

    encoders:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true


    role_hierarchy:
        ROLE_ADMIN: [ROLE_MEMBER]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/member, roles: ROLE_MEMBER }