security:
    providers:
        users:
            entity:
                class: 'App\Entity\Users'
                property: 'userEmail'

    encoders:
        App\Entity\Users:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
            form_login:
                login_path: app_login
                check_path: app_login
                provider: users
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 31536000 # 1 years in seconds
                path:     /
                token_provider: 'Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider'

                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                # always_remember_me: true

    role_hierarchy:
        ROLE_ADMIN: [ROLE_MEMBER]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/member, roles: ROLE_MEMBER }